"""Compile contract proof obligations into runnable TypeScript property tests.

An obligation is a claim about an operation. This module turns each claim into
executable code, so a contract stops being prose the reader has to trust and
becomes something a sandbox can disagree with.

Two files come out, and the split is deliberate:

* ``rich-value-generator.ts`` is identical for every project. It is the only
  place that decides what a ``ValueType`` means as a running value, so it can be
  audited once instead of once per build. It takes the type as data rather than
  compiling each type into bespoke code, which keeps the generated file small
  enough to read.
* ``obligations.test.ts`` is generated per contract and contains nothing but the
  claims themselves.

Both are protected generation inputs. A worker that could edit its own property
tests would be grading its own homework, which is the same reason the acceptance
reporter is protected.

This pack discharges ``SAMPLE`` tier only. A ``PROOF`` tier obligation asserts
something about a whole domain, and running a finite number of cases is not that
-- so rather than quietly downgrade it, scaffolding refuses.
"""

from __future__ import annotations

import json
from typing import Iterable

from ..models import (
    Contract,
    ObligationRelation,
    ObligationTier,
    OperationContract,
    ProofObligation,
    ValueType,
)


class ObligationCompileError(RuntimeError):
    """A contract cannot be expressed as property tests for this target pack."""


GENERATOR_PATH = "tests/properties/rich-value-generator.ts"
SUITE_PATH = "tests/properties/obligations.test.ts"
# The model implements this module. It is the only binding between a contract's
# operations and the source a worker writes, which is what lets a property test
# call the implementation rather than describe it.
OPERATIONS_MODULE = "packages/domain/src/operations"
# Where the pinned interface lives. Protected, and separate from the
# implementation above: the shape is the approved contract's to state, and
# only the body is the worker's to write.
OPERATIONS_INTERFACE_PATH = "packages/contracts/src/operations.ts"


VALUE_GENERATOR_SOURCE = '''\
// GENERATED BY RICH. Protected input: do not edit.
//
// Deterministic value generation for contract proof obligations. There is no
// external property-testing dependency on purpose: a failing case has to be
// reproducible from the obligation id alone, forever, on any machine, and that
// is a promise about this file rather than about a library's release notes.

export type ValueType =
  | { kind: "boolean" }
  | { kind: "integer"; minimum?: number; maximum?: number }
  | { kind: "string"; min_length?: number; max_length?: number; char_set?: CharSet }
  | { kind: "enum"; members: string[] }
  | { kind: "list"; element: ValueType; min_length?: number; max_length?: number }
  | { kind: "record"; record_fields: { name: string; value_type: ValueType }[] }
  | { kind: "optional"; element: ValueType };

export type CharSet =
  | "ascii_digits"
  | "ascii_letters"
  | "ascii_alphanumeric"
  | "ascii_identifier"
  | "ascii_slug"
  | "ascii_printable"
  | "unicode_sample";

const ASCII_DIGITS = "0123456789";
const ASCII_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

// Alphabets are arrays of code points, never strings. Indexing a string in
// JavaScript indexes UTF-16 code units, so an astral character like an emoji
// would be split and the sampler would emit a lone surrogate -- a value that
// inhabits no declared type and that the contract's own checker rejects.
const ALPHABETS: Record<CharSet, string[]> = {
  ascii_digits: Array.from(ASCII_DIGITS),
  ascii_letters: Array.from(ASCII_LETTERS),
  ascii_alphanumeric: Array.from(ASCII_LETTERS + ASCII_DIGITS),
  ascii_identifier: Array.from(ASCII_LETTERS + ASCII_DIGITS + "_"),
  ascii_slug: Array.from(ASCII_LETTERS + ASCII_DIGITS + "-_"),
  ascii_printable: Array.from({ length: 95 }, (_, i) =>
    String.fromCharCode(32 + i),
  ),
  unicode_sample: Array.from(
    ASCII_LETTERS + ASCII_DIGITS + " " + "\\u00e9\\u00fc\\u00f1\\u00e7\\u00e5" +
      "\\u65e5\\u672c\\u8a9e\\u4e2d\\u6587" + "\\ud83d\\ude42\\ud83d\\ude80" +
      "\\u05e2\\u05d1\\u05e8\\u05d9\\u05ea",
  ),
};

// Fixed bounds for an unbounded slot. A domain declared without them is
// rejected before it reaches this file, so these only ever apply to the
// optional halves of a partially bounded range.
const DEFAULT_MAX_INTEGER = 1_000_000;
const DEFAULT_MAX_LENGTH = 16;

/** xorshift32. Small, seedable, and stable across engines and versions. */
export function makeRandom(seed: number): () => number {
  let state = seed >>> 0 || 0x9e3779b9;
  return () => {
    state ^= state << 13;
    state >>>= 0;
    state ^= state >>> 17;
    state ^= state << 5;
    state >>>= 0;
    return state / 0x1_0000_0000;
  };
}

/** FNV-1a over the obligation id, so a seed is derivable and never stored. */
export function seedFrom(text: string): number {
  let hash = 0x811c9dc5;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash >>> 0;
}

function pick(random: () => number, low: number, high: number): number {
  return low + Math.floor(random() * (high - low + 1));
}

export function sample(type: ValueType, random: () => number): unknown {
  switch (type.kind) {
    case "boolean":
      return random() < 0.5;
    case "integer": {
      const minimum = type.minimum ?? -DEFAULT_MAX_INTEGER;
      const maximum = type.maximum ?? DEFAULT_MAX_INTEGER;
      return pick(random, minimum, maximum);
    }
    case "string": {
      const alphabet = ALPHABETS[type.char_set ?? "ascii_printable"];
      const minimum = type.min_length ?? 0;
      const maximum = type.max_length ?? DEFAULT_MAX_LENGTH;
      const length = pick(random, minimum, Math.max(minimum, maximum));
      let out = "";
      for (let index = 0; index < length; index += 1) {
        out += alphabet[pick(random, 0, alphabet.length - 1)];
      }
      return out;
    }
    case "enum":
      return type.members[pick(random, 0, type.members.length - 1)];
    case "list": {
      const minimum = type.min_length ?? 0;
      const maximum = type.max_length ?? DEFAULT_MAX_LENGTH;
      const length = pick(random, minimum, Math.max(minimum, maximum));
      return Array.from({ length }, () => sample(type.element, random));
    }
    case "record": {
      const out: Record<string, unknown> = {};
      for (const field of type.record_fields) {
        out[field.name] = sample(field.value_type, random);
      }
      return out;
    }
    case "optional":
      return random() < 0.25 ? null : sample(type.element, random);
  }
}

/** Structural equality over the JSON values this type language can produce. */
export function equals(left: unknown, right: unknown): boolean {
  if (Object.is(left, right)) {
    return true;
  }
  if (Array.isArray(left) && Array.isArray(right)) {
    return (
      left.length === right.length &&
      left.every((item, index) => equals(item, right[index]))
    );
  }
  if (
    typeof left === "object" &&
    typeof right === "object" &&
    left !== null &&
    right !== null
  ) {
    const leftKeys = Object.keys(left as object).sort();
    const rightKeys = Object.keys(right as object).sort();
    return (
      leftKeys.length === rightKeys.length &&
      leftKeys.every((key, index) => key === rightKeys[index]) &&
      leftKeys.every((key) =>
        equals(
          (left as Record<string, unknown>)[key],
          (right as Record<string, unknown>)[key],
        ),
      )
    );
  }
  return false;
}

/** Draw the exact case list for one obligation. Same id, same cases, always. */
export function casesFor(
  obligationId: string,
  type: ValueType,
  count: number,
): unknown[] {
  const random = makeRandom(seedFrom(obligationId));
  return Array.from({ length: count }, () => sample(type, random));
}
'''


def _identifier(operation: OperationContract) -> str:
    return operation.name


def _literal(value: object) -> str:
    """Emit a JSON value as a TypeScript literal.

    ``json.dumps`` output is valid TypeScript for every value this type language
    admits, and going through it means the emitted literal cannot disagree with
    the value the Python side validated.
    """

    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def _type_literal(value_type: ValueType) -> str:
    return _literal(value_type.to_dict())


def _case_binding(obligation: ProofObligation, domain: ValueType) -> str:
    return (
        f"  const cases = casesFor({_literal(obligation.id)}, "
        f"{_type_literal(domain)} as ValueType, {obligation.sample_size});\n"
    )


def _example_test(obligation: ProofObligation, subject: OperationContract) -> str:
    example = obligation.example
    assert example is not None
    return (
        f"it({_literal(f'{obligation.id}: {subject.name} maps a known input')}, "
        "() => {\n"
        f"  const actual = operations.{_identifier(subject)}"
        f"({_literal(example.argument)});\n"
        f"  expect(equals(actual, {_literal(example.result)})).toBe(true);\n"
        "});\n"
    )


def _relation_body(
    obligation: ProofObligation,
    subject: OperationContract,
    operands: dict[str, OperationContract | None],
) -> str:
    relation = obligation.relation
    call = f"operations.{_identifier(subject)}"
    if relation is ObligationRelation.TOTAL:
        guard = operands["guard_operation_id"]
        condition = (
            f"    if (!operations.{_identifier(guard)}(value)) continue;\n"
            if guard is not None
            else ""
        )
        return (
            "  for (const value of cases) {\n"
            f"{condition}"
            f"    expect(() => {call}(value)).not.toThrow();\n"
            "  }\n"
        )
    if relation is ObligationRelation.ROUND_TRIP:
        witness = operands["witness_operation_id"]
        assert witness is not None
        return (
            "  for (const value of cases) {\n"
            f"    const restored = operations.{_identifier(witness)}"
            f"({call}(value));\n"
            "    expect(equals(restored, value)).toBe(true);\n"
            "  }\n"
        )
    if relation is ObligationRelation.IDEMPOTENT:
        return (
            "  for (const value of cases) {\n"
            f"    const once = {call}(value);\n"
            f"    expect(equals({call}(once), once)).toBe(true);\n"
            "  }\n"
        )
    if relation is ObligationRelation.PRESERVES:
        predicate = operands["predicate_operation_id"]
        assert predicate is not None
        return (
            "  for (const value of cases) {\n"
            f"    if (!operations.{_identifier(predicate)}(value)) continue;\n"
            f"    expect(operations.{_identifier(predicate)}({call}(value)))"
            ".toBe(true);\n"
            "  }\n"
        )
    predicate = operands["predicate_operation_id"]
    assert predicate is not None
    return (
        "  for (const value of cases) {\n"
        f"    expect(operations.{_identifier(predicate)}({call}(value)))"
        ".toBe(true);\n"
        "  }\n"
    )


_RELATION_TITLES = {
    ObligationRelation.TOTAL: "never fails on its declared domain",
    ObligationRelation.ROUND_TRIP: "round-trips through its witness",
    ObligationRelation.IDEMPOTENT: "is idempotent",
    ObligationRelation.PRESERVES: "preserves its predicate",
    ObligationRelation.ESTABLISHES: "establishes its predicate",
}


def compile_obligation_suite(contract: Contract) -> str:
    """Render every obligation in one contract as a vitest suite."""

    operations = contract.operation_index
    blocks: list[str] = []
    for obligation in contract.obligations:
        if obligation.tier is not ObligationTier.SAMPLE:
            raise ObligationCompileError(
                f"obligation {obligation.id!r} claims tier "
                f"{obligation.tier.value!r}, which asserts something about the "
                "whole domain; this target pack can only run finitely many "
                "cases, and reporting that as the stronger claim would be a lie"
            )
        subject = operations[obligation.subject_operation_id]
        if obligation.relation is ObligationRelation.EXAMPLE:
            blocks.append(_example_test(obligation, subject))
            continue
        operands = {
            slot: (
                operations[getattr(obligation, slot)]
                if getattr(obligation, slot) is not None
                else None
            )
            for slot in (
                "witness_operation_id",
                "predicate_operation_id",
                "guard_operation_id",
            )
        }
        domain = subject.input_type
        if domain is None:
            raise ObligationCompileError(
                f"obligation {obligation.id!r} has no input type to draw cases "
                "from; a sample-tier claim over an undeclared domain is not a "
                "claim"
            )
        title = _RELATION_TITLES[obligation.relation]
        blocks.append(
            f"it({_literal(f'{obligation.id}: {subject.name} {title}')}, "
            "() => {\n"
            + _case_binding(obligation, domain)
            + _relation_body(obligation, subject, operands)
            + "});\n"
        )

    if not blocks:
        # A suite with no assertions passes, and a passing gate that checked
        # nothing is worse than an absent one.
        raise ObligationCompileError(
            f"contract {contract.id!r} declares no obligations, so a property "
            "gate over it would pass without checking anything"
        )

    body = "\n".join(blocks)
    relative = "../.." + "/" + OPERATIONS_MODULE
    # Import exactly what the emitted assertions use. A contract with only
    # example obligations draws no cases, and an unused import fails the very
    # typecheck and lint gates this file is supposed to run alongside.
    generator_imports = [
        name
        for name in ("casesFor", "equals")
        if f"{name}(" in body
    ]
    if "casesFor(" in body:
        generator_imports.append("type ValueType")
    return (
        "// GENERATED BY RICH. Protected input: do not edit.\n"
        "//\n"
        f"// Proof obligations declared by contract {contract.id}.\n"
        "// Each case list is drawn from the obligation id, so a failure here\n"
        "// reproduces exactly on any machine, forever.\n"
        'import { describe, expect, it } from "vitest";\n'
        "\n"
        f"import {{ {', '.join(generator_imports)} }} "
        'from "./rich-value-generator";\n'
        f'import {{ operations }} from "{relative}";\n'
        "\n"
        f"describe({_literal(contract.id)}, () => {{\n"
        + "\n".join(f"  {line}" if line else line for line in body.splitlines())
        + "\n});\n"
    )


def compile_operations_interface(contracts: Iterable[Contract]) -> str:
    """Render the typed surface a worker must implement.

    Without a pinned surface there is nothing for a property test to call, and
    a contract stays a description of software rather than a constraint on it.
    ``typecheck`` enforces the shapes; the property gate enforces the behavior.
    """

    lines: list[str] = [
        "// GENERATED BY RICH. Protected input: do not edit.\n",
        "//\n",
        "// The operations every approved contract declares. Implement this\n",
        "// interface in " + OPERATIONS_MODULE + " and export it as `operations`.\n",
    ]
    seen: dict[str, OperationContract] = {}
    for contract in contracts:
        for operation in contract.operations:
            existing = seen.get(operation.name)
            if existing is not None:
                if (
                    existing.input_type != operation.input_type
                    or existing.output_type != operation.output_type
                ):
                    raise ObligationCompileError(
                        f"operations named {operation.name!r} disagree about "
                        "their type across contracts"
                    )
                continue
            seen[operation.name] = operation

    lines.append("\nexport interface Operations {\n")
    for name in sorted(seen):
        operation = seen[name]
        if operation.input_type is None or operation.output_type is None:
            raise ObligationCompileError(
                f"operation {operation.id!r} has no declared type, so it cannot "
                "be pinned as an implementable surface"
            )
        lines.append(
            f"  {name}(input: {_typescript_type(operation.input_type)}): "
            f"{_typescript_type(operation.output_type)};\n"
        )
    lines.append("}\n")
    return "".join(lines)


def _typescript_type(value_type: ValueType) -> str:
    kind = value_type.kind.value
    if kind == "boolean":
        return "boolean"
    if kind == "integer":
        return "number"
    if kind == "string":
        return "string"
    if kind == "enum":
        return " | ".join(_literal(member) for member in value_type.members)
    if kind == "optional":
        assert value_type.element is not None
        return f"{_typescript_type(value_type.element)} | null"
    if kind == "list":
        assert value_type.element is not None
        return f"Array<{_typescript_type(value_type.element)}>"
    fields = ", ".join(
        f"{record_field.name}: {_typescript_type(record_field.value_type)}"
        for record_field in value_type.record_fields
    )
    return "{ " + fields + " }"
