"""Compile contract proof obligations into runnable TypeScript property tests.

An obligation is a claim about an operation. This module turns each claim into
executable code, so a contract stops being prose the reader has to trust and
becomes something a sandbox can disagree with.

Two files come out, and the split is deliberate:

* ``rich-value-generator.ts`` is identical for every project. It is the only
  place that decides what a ``ValueType`` means as a running value, so it can be
  audited once instead of once per build. It takes the type as data rather than
  compiling each type into bespoke code, which keeps the generated file small
  enough to read.
* ``obligations.test.ts`` is generated per contract and contains nothing but the
  claims themselves.

Both are protected generation inputs. A worker that could edit its own property
tests would be grading its own homework, which is the same reason the acceptance
reporter is protected.

This pack discharges ``SAMPLE`` tier only. A ``PROOF`` tier obligation asserts
something about a whole domain, and running a finite number of cases is not that
-- so rather than quietly downgrade it, scaffolding refuses.
"""

from __future__ import annotations

import json
import re
from typing import Iterable, Sequence

from ..models import (
    Contract,
    ObligationRelation,
    ObligationTier,
    OperationContract,
    ProofObligation,
    ValueType,
    ValueTypeKind,
)


class ObligationCompileError(RuntimeError):
    """A contract cannot be expressed as property tests for this target pack."""


GENERATOR_PATH = "tests/properties/rich-value-generator.ts"
SUITE_PATH = "tests/properties/obligations.test.ts"
# The model implements this module. It is the only binding between a contract's
# operations and the source a worker writes, which is what lets a property test
# call the implementation rather than describe it.
#
# One module per component, not one for the whole application.
#
# A single shared module made every node's implementation depend on every
# other node's contract: change a requirement the domain layer does not serve
# and its operations.ts still had to change, because it implemented the union.
# That defeats the modularity the architecture declares -- change locality is
# real at the contract level and worth nothing if the code is one lump.
def operations_module(owned_paths: Sequence[str]) -> str:
    """Where a component implements the operations it declares."""

    if not owned_paths:
        raise ObligationCompileError(
            "a component with no owned path has nowhere to implement its contract"
        )
    return f"{sorted(owned_paths)[0]}/src/operations"


def operations_interface_path(owned_paths: Sequence[str]) -> str:
    """Where its pinned interface lives: beside it, and protected."""

    return f"{operations_module(owned_paths)}-contract.ts"





VALUE_GENERATOR_SOURCE = '''\
// GENERATED BY RICH. Protected input: do not edit.
//
// Deterministic value generation for contract proof obligations. There is no
// external property-testing dependency on purpose: a failing case has to be
// reproducible from the obligation id alone, forever, on any machine, and that
// is a promise about this file rather than about a library's release notes.

export type ValueType =
  | { kind: "boolean" }
  | { kind: "integer"; minimum?: number; maximum?: number }
  | { kind: "string"; min_length?: number; max_length?: number; char_set?: CharSet }
  | { kind: "enum"; members: string[] }
  | { kind: "list"; element: ValueType; min_length?: number; max_length?: number }
  | { kind: "record"; record_fields: { name: string; value_type: ValueType }[] }
  | { kind: "optional"; element: ValueType }
  | { kind: "identifier"; entity?: string }
  | { kind: "timestamp" }
  | { kind: "date" }
  | { kind: "decimal"; precision: number; scale: number };

export type CharSet =
  | "ascii_digits"
  | "ascii_letters"
  | "ascii_alphanumeric"
  | "ascii_identifier"
  | "ascii_slug"
  | "ascii_printable"
  | "unicode_sample";

const ASCII_DIGITS = "0123456789";
const ASCII_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

// Alphabets are arrays of code points, never strings. Indexing a string in
// JavaScript indexes UTF-16 code units, so an astral character like an emoji
// would be split and the sampler would emit a lone surrogate -- a value that
// inhabits no declared type and that the contract's own checker rejects.
const ALPHABETS: Record<CharSet, string[]> = {
  ascii_digits: Array.from(ASCII_DIGITS),
  ascii_letters: Array.from(ASCII_LETTERS),
  ascii_alphanumeric: Array.from(ASCII_LETTERS + ASCII_DIGITS),
  ascii_identifier: Array.from(ASCII_LETTERS + ASCII_DIGITS + "_"),
  ascii_slug: Array.from(ASCII_LETTERS + ASCII_DIGITS + "-_"),
  ascii_printable: Array.from({ length: 95 }, (_, i) =>
    String.fromCharCode(32 + i),
  ),
  unicode_sample: Array.from(
    ASCII_LETTERS + ASCII_DIGITS + " " + "\\u00e9\\u00fc\\u00f1\\u00e7\\u00e5" +
      "\\u65e5\\u672c\\u8a9e\\u4e2d\\u6587" + "\\ud83d\\ude42\\ud83d\\ude80" +
      "\\u05e2\\u05d1\\u05e8\\u05d9\\u05ea",
  ),
};

// Fixed bounds for an unbounded slot. A domain declared without them is
// rejected before it reaches this file, so these only ever apply to the
// optional halves of a partially bounded range.
const DEFAULT_MAX_INTEGER = 1_000_000;
const DEFAULT_MAX_LENGTH = 16;
// Instants and dates are drawn from one representative century. The range is
// the sampler's, not the type's: a timestamp admits any real instant.
const EPOCH_SECONDS_2000 = 946_684_800;
const EPOCH_SECONDS_2100 = 4_102_444_800;
const EPOCH_DAYS_2000 = 10_957;
const EPOCH_DAYS_2100 = 47_482;

/** xorshift32. Small, seedable, and stable across engines and versions. */
export function makeRandom(seed: number): () => number {
  let state = seed >>> 0 || 0x9e3779b9;
  return () => {
    state ^= state << 13;
    state >>>= 0;
    state ^= state >>> 17;
    state ^= state << 5;
    state >>>= 0;
    return state / 0x1_0000_0000;
  };
}

/** FNV-1a over the obligation id, so a seed is derivable and never stored. */
export function seedFrom(text: string): number {
  let hash = 0x811c9dc5;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash >>> 0;
}

function pick(random: () => number, low: number, high: number): number {
  return low + Math.floor(random() * (high - low + 1));
}

export function sample(type: ValueType, random: () => number): unknown {
  switch (type.kind) {
    case "boolean":
      return random() < 0.5;
    case "integer": {
      const minimum = type.minimum ?? -DEFAULT_MAX_INTEGER;
      const maximum = type.maximum ?? DEFAULT_MAX_INTEGER;
      return pick(random, minimum, maximum);
    }
    case "string": {
      const alphabet = ALPHABETS[type.char_set ?? "ascii_printable"];
      const minimum = type.min_length ?? 0;
      const maximum = type.max_length ?? DEFAULT_MAX_LENGTH;
      const length = pick(random, minimum, Math.max(minimum, maximum));
      let out = "";
      for (let index = 0; index < length; index += 1) {
        out += alphabet[pick(random, 0, alphabet.length - 1)];
      }
      return out;
    }
    case "enum":
      return type.members[pick(random, 0, type.members.length - 1)];
    case "list": {
      const minimum = type.min_length ?? 0;
      const maximum = type.max_length ?? DEFAULT_MAX_LENGTH;
      const length = pick(random, minimum, Math.max(minimum, maximum));
      return Array.from({ length }, () => sample(type.element, random));
    }
    case "record": {
      const out: Record<string, unknown> = {};
      for (const field of type.record_fields) {
        out[field.name] = sample(field.value_type, random);
      }
      return out;
    }
    case "optional":
      return random() < 0.25 ? null : sample(type.element, random);
    case "identifier": {
      const alphabet = ALPHABETS.ascii_slug;
      const length = pick(random, 1, DEFAULT_MAX_LENGTH);
      let out = "";
      for (let index = 0; index < length; index += 1) {
        out += alphabet[pick(random, 0, alphabet.length - 1)];
      }
      return out;
    }
    case "timestamp":
      return new Date(
        pick(random, EPOCH_SECONDS_2000, EPOCH_SECONDS_2100) * 1000,
      ).toISOString();
    case "date":
      return new Date(pick(random, EPOCH_DAYS_2000, EPOCH_DAYS_2100) * 86_400_000)
        .toISOString()
        .slice(0, 10);
    case "decimal": {
      // Digits, never a number: the value is a string end to end, so nothing
      // here can round. At most `precision - scale` integer digits and at
      // most `scale` fractional ones, in any of the spellings the checker
      // admits.
      const integerDigits = Math.max(0, type.precision - type.scale);
      const wholeLength = integerDigits === 0 ? 0 : pick(random, 1, integerDigits);
      let whole = "";
      for (let index = 0; index < wholeLength; index += 1) {
        whole += ASCII_DIGITS[pick(random, index === 0 ? 1 : 0, 9)];
      }
      if (whole === "") whole = "0";
      const fractionLength = pick(random, 0, type.scale);
      let fraction = "";
      for (let index = 0; index < fractionLength; index += 1) {
        fraction += ASCII_DIGITS[pick(random, 0, 9)];
      }
      const magnitude = fraction === "" ? whole : `${whole}.${fraction}`;
      const negative = random() < 0.5 && canonicalDecimal(magnitude) !== "0";
      return negative ? `-${magnitude}` : magnitude;
    }
  }
}

/**
 * The canonical form of a value under its type. A decimal loses its leading
 * and trailing zeros -- "01.50" and "1.5" are one value -- and nothing else
 * changes. Assertions over a type that carries a decimal compare after this,
 * because an implementation is right to answer "1.5" where the contract
 * wrote "1.50".
 */
export function normalize(type: ValueType, value: unknown): unknown {
  switch (type.kind) {
    case "decimal":
      return typeof value === "string" ? canonicalDecimal(value) : value;
    case "optional":
      return value === null ? null : normalize(type.element, value);
    case "list":
      return Array.isArray(value)
        ? value.map((item) => normalize(type.element, item))
        : value;
    case "record": {
      if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return value;
      }
      const record = value as Record<string, unknown>;
      const out: Record<string, unknown> = { ...record };
      for (const field of type.record_fields) {
        if (field.name in record) {
          out[field.name] = normalize(field.value_type, record[field.name]);
        }
      }
      return out;
    }
    default:
      return value;
  }
}

function canonicalDecimal(text: string): string {
  const match = /^(-?)(\\d+)(?:\\.(\\d+))?$/.exec(text);
  if (match === null) return text;
  const whole = (match[2] ?? "0").replace(/^0+(?=\\d)/, "");
  const fraction = (match[3] ?? "").replace(/0+$/, "");
  const magnitude = fraction === "" ? whole : `${whole}.${fraction}`;
  return magnitude === "0" || match[1] === "" ? magnitude : `-${magnitude}`;
}

/**
 * Run an operation and report what it threw, or null. A totality claim in
 * one value, and one that reads the same whether the operation answers
 * synchronously or with a promise.
 */
export async function thrown(run: () => unknown): Promise<unknown> {
  try {
    await run();
    return null;
  } catch (error) {
    return error === undefined ? new Error("threw undefined") : error;
  }
}

/** Structural equality over the JSON values this type language can produce. */
export function equals(left: unknown, right: unknown): boolean {
  if (Object.is(left, right)) {
    return true;
  }
  if (Array.isArray(left) && Array.isArray(right)) {
    return (
      left.length === right.length &&
      left.every((item, index) => equals(item, right[index]))
    );
  }
  if (
    typeof left === "object" &&
    typeof right === "object" &&
    left !== null &&
    right !== null
  ) {
    const leftKeys = Object.keys(left as object).sort();
    const rightKeys = Object.keys(right as object).sort();
    return (
      leftKeys.length === rightKeys.length &&
      leftKeys.every((key, index) => key === rightKeys[index]) &&
      leftKeys.every((key) =>
        equals(
          (left as Record<string, unknown>)[key],
          (right as Record<string, unknown>)[key],
        ),
      )
    );
  }
  return false;
}

/** Draw the exact case list for one obligation. Same id, same cases, always. */
export function casesFor(
  obligationId: string,
  type: ValueType,
  count: number,
): unknown[] {
  const random = makeRandom(seedFrom(obligationId));
  return Array.from({ length: count }, () => sample(type, random));
}
'''


def _identifier(operation: OperationContract) -> str:
    return operation.name


def _literal(value: object) -> str:
    """Emit a JSON value as a TypeScript literal.

    ``json.dumps`` output is valid TypeScript for every value this type language
    admits, and going through it means the emitted literal cannot disagree with
    the value the Python side validated.
    """

    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def _type_literal(value_type: ValueType) -> str:
    return _literal(value_type.to_dict())


def _case_binding(obligation: ProofObligation, domain: ValueType) -> str:
    return (
        f"  const cases = casesFor({_literal(obligation.id)}, "
        f"{_type_literal(domain)} as ValueType, {obligation.sample_size});\n"
    )


def _carries_decimal(value_type: ValueType | None) -> bool:
    if value_type is None:
        return False
    if value_type.kind is ValueTypeKind.DECIMAL:
        return True
    if value_type.element is not None and _carries_decimal(value_type.element):
        return True
    return any(
        _carries_decimal(record_field.value_type)
        for record_field in value_type.record_fields
    )


def _shape_binding(value_type: ValueType | None) -> str:
    """Bind the type an assertion normalises under, when it must.

    Only a type that carries a decimal needs one: "1.5" and "1.50" are one
    value, and an implementation is right to answer either. Every other
    type compares structurally, as before, so suites over them are unchanged.
    """

    if not _carries_decimal(value_type):
        return ""
    assert value_type is not None
    return f"  const shape = {_type_literal(value_type)} as ValueType;\n"


def _equal(actual: str, expected: str, value_type: ValueType | None) -> str:
    if _carries_decimal(value_type):
        return (
            f"expect(normalize(shape, {actual}))"
            f".toEqual(normalize(shape, {expected}))"
        )
    # toEqual, not equals(...) collapsed to a boolean: vitest prints the
    # diff, and "expected false to be true" tells a reader -- or the worker
    # reading the gate output on its next attempt -- nothing at all.
    return f"expect({actual}).toEqual({expected})"


def _example_test(obligation: ProofObligation, subject: OperationContract) -> str:
    example = obligation.example
    assert example is not None
    return (
        f"it({_literal(f'{obligation.id}: {subject.name} maps a known input')}, "
        "async () => {\n"
        + _shape_binding(subject.output_type)
        + f"  const actual = await operations.{_identifier(subject)}"
        f"({_literal(example.argument)});\n"
        f"  {_equal('actual', _literal(example.result), subject.output_type)};\n"
        "});\n"
    )


def _relation_body(
    obligation: ProofObligation,
    subject: OperationContract,
    operands: dict[str, OperationContract | None],
) -> str:
    # Every call is awaited. An operation may answer synchronously or with a
    # promise -- the interface says `O | Promise<O>` -- and `await` of a plain
    # value is that value, so one spelling serves both.
    relation = obligation.relation
    call = f"operations.{_identifier(subject)}"
    if relation is ObligationRelation.TOTAL:
        guard = operands["guard_operation_id"]
        condition = (
            f"    if (!(await operations.{_identifier(guard)}(value))) continue;\n"
            if guard is not None
            else ""
        )
        return (
            "  for (const value of cases) {\n"
            f"{condition}"
            f"    expect(await thrown(() => {call}(value))).toBeNull();\n"
            "  }\n"
        )
    if relation is ObligationRelation.ROUND_TRIP:
        witness = operands["witness_operation_id"]
        assert witness is not None
        return (
            "  for (const value of cases) {\n"
            f"    const restored = await operations.{_identifier(witness)}"
            f"(await {call}(value));\n"
            f"    {_equal('restored', 'value', subject.input_type)};\n"
            "  }\n"
        )
    if relation is ObligationRelation.IDEMPOTENT:
        return (
            "  for (const value of cases) {\n"
            f"    const once = await {call}(value);\n"
            f"    {_equal(f'await {call}(once)', 'once', subject.output_type)};\n"
            "  }\n"
        )
    if relation is ObligationRelation.PRESERVES:
        predicate = operands["predicate_operation_id"]
        assert predicate is not None
        return (
            "  for (const value of cases) {\n"
            f"    if (!(await operations.{_identifier(predicate)}(value))) continue;\n"
            f"    expect(await operations.{_identifier(predicate)}"
            f"(await {call}(value))).toBe(true);\n"
            "  }\n"
        )
    predicate = operands["predicate_operation_id"]
    assert predicate is not None
    return (
        "  for (const value of cases) {\n"
        f"    expect(await operations.{_identifier(predicate)}"
        f"(await {call}(value))).toBe(true);\n"
        "  }\n"
    )


_RELATION_TITLES = {
    ObligationRelation.TOTAL: "never fails on its declared domain",
    ObligationRelation.ROUND_TRIP: "round-trips through its witness",
    ObligationRelation.IDEMPOTENT: "is idempotent",
    ObligationRelation.PRESERVES: "preserves its predicate",
    ObligationRelation.ESTABLISHES: "establishes its predicate",
}


def compile_obligation_suite(
    contract: Contract, owned_paths: Sequence[str] = ()
) -> str:
    """Render every obligation in one contract as a vitest suite."""

    operations = contract.operation_index
    blocks: list[str] = []
    for obligation in contract.obligations:
        if obligation.tier is not ObligationTier.SAMPLE:
            raise ObligationCompileError(
                f"obligation {obligation.id!r} claims tier "
                f"{obligation.tier.value!r}, which asserts something about the "
                "whole domain; this target pack can only run finitely many "
                "cases, and reporting that as the stronger claim would be a lie"
            )
        subject = operations[obligation.subject_operation_id]
        if obligation.relation is ObligationRelation.EXAMPLE:
            blocks.append(_example_test(obligation, subject))
            continue
        operands = {
            slot: (
                operations[getattr(obligation, slot)]
                if getattr(obligation, slot) is not None
                else None
            )
            for slot in (
                "witness_operation_id",
                "predicate_operation_id",
                "guard_operation_id",
            )
        }
        domain = subject.input_type
        if domain is None:
            raise ObligationCompileError(
                f"obligation {obligation.id!r} has no input type to draw cases "
                "from; a sample-tier claim over an undeclared domain is not a "
                "claim"
            )
        title = _RELATION_TITLES[obligation.relation]
        compared = (
            subject.input_type
            if obligation.relation is ObligationRelation.ROUND_TRIP
            else subject.output_type
        )
        blocks.append(
            f"it({_literal(f'{obligation.id}: {subject.name} {title}')}, "
            "async () => {\n"
            + _case_binding(obligation, domain)
            + (
                _shape_binding(compared)
                if obligation.relation
                in (ObligationRelation.ROUND_TRIP, ObligationRelation.IDEMPOTENT)
                else ""
            )
            + _relation_body(obligation, subject, operands)
            + "});\n"
        )

    if not blocks:
        # A suite with no assertions passes, and a passing gate that checked
        # nothing is worse than an absent one.
        raise ObligationCompileError(
            f"contract {contract.id!r} declares no obligations, so a property "
            "gate over it would pass without checking anything"
        )

    body = "\n".join(blocks)
    module = operations_module(owned_paths) if owned_paths else "packages/domain/src/operations"
    relative = "../.." + "/" + module
    # Import exactly what the emitted assertions use. A contract with only
    # example obligations draws no cases, and an unused import fails the very
    # typecheck and lint gates this file is supposed to run alongside.
    # A bare call, never a method: an operation may be named `normalize` or
    # `equals`, and `operations.normalize(` must not pull the generator's.
    generator_imports = [
        name
        for name in ("casesFor", "equals", "normalize", "thrown")
        if re.search(rf"(?<![\w.]){name}\(", body)
    ]
    if "as ValueType" in body:
        generator_imports.append("type ValueType")
    return (
        "// GENERATED BY RICH. Protected input: do not edit.\n"
        "//\n"
        f"// Proof obligations declared by contract {contract.id}.\n"
        "// Each case list is drawn from the obligation id, so a failure here\n"
        "// reproduces exactly on any machine, forever.\n"
        'import { describe, expect, it } from "vitest";\n'
        "\n"
        + (
            f"import {{ {', '.join(generator_imports)} }} "
            'from "./rich-value-generator";\n'
            if generator_imports
            else ""
        )
        + f'import {{ operations }} from "{relative}";\n'
        "\n"
        f"describe({_literal(contract.id)}, () => {{\n"
        + "\n".join(f"  {line}" if line else line for line in body.splitlines())
        + "\n});\n"
    )


def compile_operations_interface(
    contracts: Iterable[Contract], owned_paths: Sequence[str] = ()
) -> str:
    """Render the typed surface a worker must implement.

    Without a pinned surface there is nothing for a property test to call, and
    a contract stays a description of software rather than a constraint on it.
    ``typecheck`` enforces the shapes; the property gate enforces the behavior.
    """

    lines: list[str] = [
        "// GENERATED BY RICH. Protected input: do not edit.\n",
        "//\n",
        "// The operations this component's approved contract declares.\n"
        "// Implement this\n",
        "// interface in "
        + (operations_module(owned_paths) if owned_paths else "its module")
        + " and export it as `operations`.\n",
        "//\n",
        "// Every operation may answer synchronously or with a promise. The\n",
        "// property gate awaits every call, so a component that reaches a\n",
        "// database answers with promises and one that does not need not.\n",
    ]
    seen: dict[str, OperationContract] = {}
    for contract in contracts:
        for operation in contract.operations:
            existing = seen.get(operation.name)
            if existing is not None:
                if (
                    existing.input_type != operation.input_type
                    or existing.output_type != operation.output_type
                ):
                    raise ObligationCompileError(
                        f"operations named {operation.name!r} disagree about "
                        "their type across contracts"
                    )
                continue
            seen[operation.name] = operation

    if any(
        _carries_decimal(operation.input_type) or _carries_decimal(operation.output_type)
        for operation in seen.values()
    ):
        lines.append(
            "\n"
            "/**\n"
            " * An exact number carried as a string, never a float: \"12.50\".\n"
            " * The declared precision and scale are held by the property gate,\n"
            " * not the type system. Make one with `value as Decimal`.\n"
            " */\n"
            "export type Decimal = string & { readonly __rich_decimal: never };\n"
        )

    lines.append("\nexport interface Operations {\n")
    for name in sorted(seen):
        operation = seen[name]
        if operation.input_type is None or operation.output_type is None:
            raise ObligationCompileError(
                f"operation {operation.id!r} has no declared type, so it cannot "
                "be pinned as an implementable surface"
            )
        output = _typescript_type(operation.output_type)
        lines.append(
            f"  {name}(input: {_typescript_type(operation.input_type)}): "
            f"{output} | Promise<{output}>;\n"
        )
    lines.append("}\n")
    return "".join(lines)


def _typescript_type(value_type: ValueType) -> str:
    kind = value_type.kind.value
    if kind == "boolean":
        return "boolean"
    if kind == "integer":
        return "number"
    if kind in ("string", "identifier", "timestamp", "date"):
        # An identifier, an instant and a date are strings with a grammar the
        # gate checks; only a decimal is branded, because a plain string
        # there would invite a float on the way in.
        return "string"
    if kind == "decimal":
        return "Decimal"
    if kind == "enum":
        return " | ".join(_literal(member) for member in value_type.members)
    if kind == "optional":
        assert value_type.element is not None
        return f"{_typescript_type(value_type.element)} | null"
    if kind == "list":
        assert value_type.element is not None
        return f"Array<{_typescript_type(value_type.element)}>"
    fields = ", ".join(
        f"{record_field.name}: {_typescript_type(record_field.value_type)}"
        for record_field in value_type.record_fields
    )
    return "{ " + fields + " }"
