"""Generated entrypoint — assembly fold for the build tree.

This file is generated by build.py (§6.2). Do not edit by hand.
"""


def _wiring_class(module, module_id):
    """Return the single class DEFINED in `module` — the verified wiring class.

    Fail loud if not exactly one (§6: assembly never guesses composition).
    """
    import inspect
    own = [c for _n, c in inspect.getmembers(module, inspect.isclass)
           if c.__module__ == module_id]
    if len(own) != 1:
        raise RuntimeError(
            f"assemble[{module_id}]: expected exactly ONE wiring class defined "
            f"in the module, found {[c.__name__ for c in own]!r}. v1 supports a "
            f"single injected wiring class per node; refusing to guess.")
    return own[0]


# Wiring node: comment_ingest — instantiate verified class, inject ['sanitize', 'moderate', 'enrich', 'format']
def construct_comment_ingest(sanitize, moderate, enrich, format):
    import comment_ingest as _m
    return _wiring_class(_m, 'comment_ingest')(sanitize=sanitize, moderate=moderate, enrich=enrich, format=format)

# Module (no injected deps): enrich — wraps top-level functions
def construct_enrich():
    import enrich as _m
    class _Handle:
        def enrich(self, *args, **kwargs):
            return _m.enrich(*args, **kwargs)
    return _Handle()

# Module (no injected deps): format — wraps top-level functions
def construct_format():
    import format as _m
    class _Handle:
        def format(self, *args, **kwargs):
            return _m.format(*args, **kwargs)
    return _Handle()

# Module (no injected deps): moderate — wraps top-level functions
def construct_moderate():
    import moderate as _m
    class _Handle:
        def moderate(self, *args, **kwargs):
            return _m.moderate(*args, **kwargs)
    return _Handle()

# Module (no injected deps): sanitize — wraps top-level functions
def construct_sanitize():
    import sanitize as _m
    class _Handle:
        def sanitize(self, *args, **kwargs):
            return _m.sanitize(*args, **kwargs)
    return _Handle()


def assemble():
    """Deterministic topological fold — inject dependencies by name."""

    moderate = construct_moderate()
    enrich = construct_enrich()
    format = construct_format()
    sanitize = construct_sanitize()
    comment_ingest = construct_comment_ingest(sanitize=sanitize, moderate=moderate, enrich=enrich, format=format)

    return comment_ingest


if __name__ == '__main__':
    demo = assemble()
    result = demo.ingest('test input')
    print('ingest result:', result)
    print('✓ Deliverable: OK')
